// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Configuration Supabase
const SUPABASE_URL = "https://bkdcbrnfzgnafjwnryme.supabase.co";

// La clé peut être expirée ou invalide, c'est probablement la source de l'erreur
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrZGNicm5memduYWZqd25yeW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2ODA1MTAsImV4cCI6MjA2MTI1NjUxMH0.cdzP9f_Bg1TlrBs-v1DsOb5Iv-tfK0KURPwZn1hwYMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Logs de diagnostic pour la connexion
console.log('🔌 Initialisation de la connexion Supabase...');
console.log('URL:', SUPABASE_URL);
console.log('Clé API (début):', SUPABASE_PUBLISHABLE_KEY.substring(0, 10) + '...');

// Créer le client avec plus d'options de debug
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
    },
    global: {
      fetch: (url: RequestInfo | URL, options?: RequestInit) => {
        // Pour aider au débogage des requêtes Supabase
        console.log('🔄 Supabase fetch:', typeof url === 'string' ? url : url.toString());
        return fetch(url, options).then(response => {
          console.log(`📡 Réponse (${response.status}):`, response.ok ? 'OK' : 'ERREUR');
          return response;
        }).catch(error => {
          console.error('❌ Erreur fetch Supabase:', error);
          throw error;
        });
      }
    }
  }
);

// Vérification immédiate de la connexion
(async () => {
  try {
    console.log('🔍 Test de connexion Supabase...');
    const { data, error } = await supabase.from('samples').select('count');
    if (error) {
      console.error('❌ Erreur de connexion à Supabase:', error);
    } else {
      console.log('✅ Connexion Supabase fonctionnelle. Données:', data);
    }
  } catch (err) {
    console.error('❌ Exception lors du test de connexion Supabase:', err);
  }
})();

// Exporter des informations de débogage
(supabase as any).supabaseUrl = SUPABASE_URL;
(supabase as any).supabaseKey = SUPABASE_PUBLISHABLE_KEY;